language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

sudo: false

install:
  - 'if [ $(phpenv version-name) == "5.5" ]; then rm ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini; fi'
  - 'if [ $(phpenv version-name) != "hhvm" ] && [ $(phpenv version-name) != "nightly" ]; then echo "xdebug.overload_var_dump = 0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi'
  - 'if [ $(phpenv version-name) == "7.2" ] && [ -v COMPOSER_OPTS ]; then composer require --dev phpunit/phpunit "^5.7.11"; fi'
  - 'if [ $(phpenv version-name) == "7.1" ]; then composer require --dev leanphp/behat-code-coverage:v3.0.0;mv behat.dist behat.yml; fi'
  - composer --version
  - travis_retry composer update $COMPOSER_OPTS --no-interaction --prefer-source

script:
  - make behat

after_success:
  - 'if [ $(phpenv version-name) == "7.1" ]; then curl -s https://codecov.io/bash | bash; fi'